### ISSUE TITLE
Merge upstream changes

### ISSUE THREAD

**Issue by peterhaochen47** [thales-e-security/envoy#23]
We are trying to work off a newer istio source code. Today we are working off istio/1.1-snapshot.2, and we would like to move to istio/1.1-snapshot.6, which requires a newer envoy source code. We checked that the linked envoy commit is this one: https://github.com/envoyproxy/envoy/commit/925810d00b0d3095a8e67fd4e04e0f597ed188bb (made on Feb 8, 2019).

We are wondering if you could bring in those newer envoy commits to your envoy fork?

**Comment by cameronmoreau** [comment]
Istio has released [a 1.1.0 version](https://github.com/istio/istio/releases/) that is now using [this version of Envoy](https://github.com/envoyproxy/envoy/commit/925810d00b0d3095a8e67fd4e04e0f597ed188bb) with the commit id `925810d`.

We are trying to build istio proxy on the new 1.1.0 tag but it appears that Envoy has quite a few changes (such as new bazel deps) which makes this fork currently incompatible with istio-proxy 1.1.0.
```
ERROR: Failed to load Starlark extension '@rules_foreign_cc//:workspace_definitions.bzl'.
It usually happens when the repository is not defined prior to being used.
```

@nickrmc83, would you be able to provide a timeline of when you could merge the fork to the mentioned commit?

Thanks! 🙌

**Comment by nickrmc83** [comment]
We can take a look next week. How long we're not sure yet. Will advise next week.

**Comment by peterhaochen47** [comment]
Update: [Istio 1.1.1](https://github.com/istio/istio/releases/) is out

**Comment by sburton84** [comment]
I have rebased our changes onto the head of the Envoy master branch and this is on the branch `newoidc`. I have also backported these changes onto the `925810d` commit and this is on the branch `istio-1.1.0-oidc`, so this branch is what you probably want to try using with Istio 1.1.
