### ISSUE TITLE
Allow oidc filter to be given a local_jwks/inline_string as an input

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#5]
Envoy currently supports a `local_jwks` and `remote_jwks` for the jwt_authn filter.
[Example](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto#envoy-api-msg-config-filter-http-jwt-authn-v2alpha-jwtauthentication). We noticed that istio will fetch the jwks and configure envoy as an `inline_string` when applying the jwt authentication policy. 

Is it possible to match this functionality? i.e. `remote_jwks` could be given an `http_uri`; and `local_jwks` could be given an `inline_string` or filename.

Related question: https://istio.slack.com/archives/CCTF68KGF/p1542067928033000

**Comment by nickrmc83** [comment]
I'll replicate the JWT_AuthN filter config.

**Comment by nickrmc83** [comment]
Fixed in 774cb24fd660f6b971e8aea25f9d4c0c5c040b09
