### ISSUE TITLE
jwks_fetcher doesn't accept "application/json;charset=UTF-8"

### ISSUE THREAD

**Issue by peterhaochen47** [thales-e-security/envoy#7]
[This line](https://github.com/thales-e-security/envoy/blob/oidc/source/extensions/filters/http/common/jwks_fetcher.cc#L14) seems to be restricting jwks Content-Type response header to only "application/json; charset=UTF-8" (notice the space after semicolon)? So "application/json;charset=UTF-8" (also a valid header value) doesn't go through because it has no space after semicolon.

**Comment by nickrmc83** [comment]
Yes this is an error. I'll add some facility to allow
`application/json`, `application/json;charset=UTF-8` or `application/json; charset=UTF-8`

**Comment by nickrmc83** [comment]
Fixed by 1aeaf2570de792efe2d357b1dd1ea32c7c672b13
