### ISSUE TITLE
1/9 meetup agenda

### ISSUE THREAD

**Issue by peterhaochen47** [thales-e-security/envoy#8]
Meeting notes:

1. Going over issues and topics arising from testing the WIP oidc + session_manager filter:
- Currently, the obtained token is still stored as cookies unencrypted, which is expected due to the WIP nature of the filter. The next step is to store an encrypted version in cookies to represent a session.
- We should keep in mind the size/security limitations of cookies; but no action items for now.
- Currently, the token name (Cookies key) is hardcoded and thus only works when the `token_binding.token` is set to `istio_session`. The next step is to make this configurable as something like `__Secure-acme-session-cookie-name`.
- The `nonce` value being used to make Oauth calls seems to be hardcoded? => needs verification.
- There is discussions surrounding how to best forward down or persist the `id token` vs `access token` (both obtained by the oidc filter, and currently only `id token` is stored and consumed). => Needs more research on OIDC/Oauth specs. 

2. KubeCon Europe talk.

**Comment by willsu** [comment]
@nickrmc83 would it be possible to add our GitHub team, rather than the individual contributors? If not, I can provide a list of the individual. 

https://github.com/orgs/pivotal/teams/pcf-app-sso

**Comment by willsu** [comment]
@nickrmc83 Regarding Browser support, here is a list from the open source Cloud Foundry project that is the closest to what our apps will support :).

https://github.com/cloudfoundry/uaa-singular#compatibility

**Comment by willsu** [comment]
@nickrmc83 Provided that we agree that Access Tokens should be used to access Secured APIs (i.e. downstream services) we should probably talk a bit more how these various tokens will be stored. We can continue the discussion about whether or not both tokens will be entirely necessary, but I'm just assuming that they are for the purposes of this comment. 

Goals:
* Keep the token acquisition/management portion of this envoy fork stateless, if possible.

Stateless:
1) ID and Access tokens may be represented as separate, encrypted cookies stored in the end user's User Agent.

Pros:
* Allows us to remain stateless, thus considerably reducing operational complexities.

Cons:
* ID and Access tokens, although encrypted, will be exposed to the end users. If our encryption keys are ever compromised, then we can only assume that all tokens encrypted using that encryption key (even though the far majority will be expired) will be readable in plain text.
* No good way to store tokens acquired using Client Credentials (non-user-agent based) flows.. Or is there? This would mean that Access tokens acquired with Client Credentials would need to used immediately (in-band), as opposed to using the Access Tokens being accessible for the whole lifespan of their TTL.

Stateful (Backed with Persistent Store):
(To be Continued..)

**Comment by nickrmc83** [comment]
@willsu in relation to the use of tokens, the design being presented does not currently look to enforce access control (authorization) on a user/service/app attempting to access an API using an identity token which is what I believe your link is referring to and what's defined in the OAuth2 framework. It instead looks to acquire tokens that may be used in downstream authorization decisions and inline with the design outlined [here](https://docs.google.com/document/d/1rU0OgZ0vGNXVlm_WjA-dnfQdS3BsyqmqXnu254pFnZg) where user tokens are swapped with internal tokens. This is a fundamental difference to how OAuth2 generally works where the authorization token carries the callers rights (via claims) as asserted by an authorization server. This design instead looks to support istio's just-in-time authorization policies so that a user's identity is used at the point of an API call to assert their access rights. It's a difference between just-in-time and upfront authorization. In reality though I think an access token can be used in place of an identity token if it carries identity claims via a standard set of JWT claims but it's important to understand the token doesn't carry any authorization semantics, just authentication.

**Comment by nickrmc83** [comment]
@willsu I've tried to add the Pivotal team as collaborators but it looks like I need to add you all as individuals. Can you PM me github aliases of people who want/need access?

**Comment by willsu** [comment]
Thanks for your reply @nickrmc83. I had a brief conversation with our product manager, Tian, who helped me better get my head around the scope of what you're working on, vs the wholistic picture of what Pivotal would like our product to accomplish. I'm still carefully unraveling the conceptual layers, so thanks for bearing with me. 

Here is my understanding of your work:
You work focuses on implementing the various OpenIDC token grant flows. More specifically, the flows that you implement will be those that can originate from public clients (i.e. and end user web browser). That said, the implementation of various authorization filters for JWTs/opaque tokens/etc will be handled independently from your work stream.

Current State:
The ID token is propagated to the oauth client application (currently through a cookie)

Desired State:
Both the ID and Access token's are propagated to the oauth client application. The oauth client application need not validate/introspect the Access token.. However, the oauth client application may use the Access Token to request resources from downstream services. The oauth client application will, however, use the ID token directly for a variety of reasons (i.e. populating user identity information in the DOM). Exactly how the oauth client application receives these tokens will probably be an ongoing discussion and implementation details will change. However, we are confident that the Access Token retrieved during the various OIDC authentication flows will be needed to access data from downstream services.

Do you think our goals align here? I can definitely provide more context and use cases as needed. I hope I'm not coming across as too abrupt or demanding, just trying to be (hopefully) more clear.

**Comment by willsu** [comment]
@nickrmc83 

> Can you PM me github aliases of people who want/need access?
Sure thing!

```
aashah
aramprice
cameronmoreau
jberney
peterhaochen47
tnwang
willsu
```

Thanks.

**Comment by nickrmc83** [comment]
Collaborators added!
